#####################################################
# CNAP integrated applications configurations
# Applied as CNAP sub-charts overrides
#####################################################
kong-ingress-controller:
  enabled: true
  gateway:
    deployment:
      userDefinedVolumes:
      - name: keycloak-ca-volume
        secret:
          secretName: cnap-keycloak-crt
      userDefinedVolumeMounts:
      - name: keycloak-ca-volume
        mountPath: /etc/secrets/keycloak
        readOnly: true
    env:
      lua_ssl_trusted_certificate: "/etc/secrets/keycloak/ca.crt"    
    plugins:
      configMaps:
      - name: kong-plugin-oidc  # Reference to the ConfigMap created for the OIDC plugin
        pluginName: oidc  # The name of the plugin which kong will use
        
keycloak:
  enabled: true
  image:
    repository: bitnamilegacy/keycloak
    tag: 20.0.5-debian-11-r2
    debug: true
  extraEnvVars:
  - name: KC_LOG_LEVEL
    value: INFO,org.keycloak.protocol.oidc:debug,org.keycloak.events:debug
  - name: KC_HOSTNAME_URL
    value: https://127.0.0.1:30443/auth
  - name: KC_PROXY
    value: edge
  - name: KC_HOSTNAME_STRICT
    value: "false"
  - name: KC_HOSTNAME_STRICT_BACKCHANNEL
    value: "true"
  auth:
    adminUser: "admin"
    adminPassword: "adpass"
  postgresql:
    enabled: true
    image:
      repository: bitnamilegacy/postgresql
      tag: 15.2.0-debian-11-r31
    auth:
      username: "keycloak"
      password: "keycloakdbuser"
      database: "keycloak"
  # -- Since keycloak 17+, default to / but the controllers work with older versions
  httpRelativePath: "/auth/"
  #proxy: edge
  tls:
   enabled: true
   autoGenerated: true
  #extraEnvVars:
  #  - name: PROXY_ADDRESS_FORWARDING
  #    value: "true"
  ##
  # -- Keycloak LoadBalancer and Headless ClusterIp service port
  service:
    ports: &portKeycloak
      http: 8083
      https: 8443
  # -- Keycloak HTTP container port
  containerPorts: *portKeycloak

operator-applications:
  enabled: true

kube-prometheus-stack:
  enabled: true

################################################################################
# CNAP Specific Configurations
# Not always applied as sub-charts overrides
# May also used by other scripts/apps/operators in their codebase
################################################################################
cnap:
  kong-ingress-controller:
    plugins:
      oidc:
        config:
          client_id: "api-auth-client"
          client_secret: "6QsqpfVECQaNoBYE4Qto7CPW8JuqZwL1"
          token_validation_url: "https://cnap-keycloak.cnap.svc.cluster.local:8443/auth/realms/api-auth/protocol/openid-connect/token/introspect"
