apiVersion: cnap.platforms.howlabs.io/v1alpha1
kind: Application
metadata:
  name: example-app
  namespace: cnap
spec:
  integrations:
    gateway:
      name: kong-ingress-controller  # Name of the gateway to use
      addons:
        - name: plugins
          resources:
            - resourceName: ingress
              addonResourceName:
                - "kongplugin-oidc"  # Operator will look for this string to Add/Remove

  global:
    baseDomain: api.example.com
    envPrefix:
      - env: dev
        prefix: dev
      - env: prod
        prefix: ""
    authentication:
      enabled: true
      methods:
        basicAuth: false
        apiToken: true
    singleSignOn:
      enabled: false
      methods:
        saml: false
        oauth2: false
        oidc: false

  components:
    - name: api-service
      routes:
        - summary: "Status API"
          path: /api/status
          method: GET
          exposedAPI: true
          httpsEnabled: true
          whitelistIPs:
            - 10.0.0.0/24
        - summary: "Homepage API"
          path: /
          method: GET
          exposedAPI: true
          httpsEnabled: false
